<?php
/**
 * Copyright since 2007 PrestaShop SA and Contributors
 * PrestaShop is an International Registered Trademark & Property of PrestaShop SA
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License version 3.0
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * @author    PrestaShop SA and Contributors <contact@prestashop.com>
 * @copyright Since 2007 PrestaShop SA and Contributors
 * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License version 3.0
 */

declare(strict_types=1);

namespace PrestaShop\Module\APIResources\ApiPlatform\Resources\Product;

use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Parameters;
use ApiPlatform\Metadata\QueryParameter;
use ApiPlatform\OpenApi\Model\Operation as OpenApiOperation;
use PrestaShop\PrestaShop\Core\Domain\Product\Exception\ProductNotFoundException;
use PrestaShop\PrestaShop\Core\Domain\Product\Stock\Exception\StockAvailableNotFoundException;
use PrestaShop\PrestaShop\Core\Domain\Product\Stock\Query\GetProductStockMovements;
use PrestaShop\PrestaShop\Core\Domain\Product\Stock\QueryResult\StockMovement;
use PrestaShopBundle\ApiPlatform\Metadata\CQRSGetCollection;
use Symfony\Component\HttpFoundation\Response;

#[ApiResource(
    operations: [
        new CQRSGetCollection(
            uriTemplate: '/products/{productId}/stock-movements',
            // The pagination of this endpoint relies on its own offset and limit parameters, so the page
            // parameter ApiPlatform documents by default on every collection operation would be misleading
            paginationEnabled: false,
            CQRSQuery: GetProductStockMovements::class,
            scopes: ['product_read'],
            openapi: new OpenApiOperation(
                summary: 'Get the stock movements of a product.',
                description: 'Returns the stock movement history of the product, latest first, grouped the same way '
                    . 'as the stock movements tab of the product page in the back office. Each item is a group of '
                    . 'movements, not a single movement: an `edition` item is one manual stock update (made by an '
                    . 'employee in the back office, or by an API client through this API) and holds a single '
                    . 'movement, while an `orders` item aggregates all the consecutive movements generated by '
                    . 'customer orders between two editions. This is why the identifiers are lists: '
                    . '`stockMovementIds`, `stockIds`, `orderIds`, `employeeIds` and `apiClientIds` hold one entry '
                    . 'per movement of the group (a single one for an edition, several for an orders group). '
                    . '`deltaQuantity` is the sum of the quantities of the group, and `dates` holds the `add` date '
                    . 'of an edition or the `from` / `to` range of an orders group.',
            ),
            CQRSQueryMapping: [
                '[_context][shopId]' => '[shopId]',
            ],
            parameters: new Parameters([
                new QueryParameter(
                    key: 'offset',
                    schema: ['type' => 'integer'],
                    required: false,
                    description: 'Number of movements to skip (for pagination).'
                ),
                new QueryParameter(
                    key: 'limit',
                    schema: ['type' => 'integer'],
                    required: false,
                    description: 'Maximum number of movements to return.'
                ),
            ]),
            openapiContext: [
                'parameters' => [
                    [
                        'name' => 'offset',
                        'in' => 'query',
                        'required' => false,
                        'schema' => [
                            'type' => 'integer',
                            'minimum' => 0,
                            'default' => 0,
                        ],
                        'description' => 'Number of movements to skip (for pagination).',
                    ],
                    [
                        'name' => 'limit',
                        'in' => 'query',
                        'required' => false,
                        'schema' => [
                            'type' => 'integer',
                            'minimum' => 0,
                            'default' => GetProductStockMovements::DEFAULT_LIMIT,
                        ],
                        'description' => 'Maximum number of movements to return.',
                    ],
                ],
            ],
        ),
    ],
    exceptionToStatus: [
        ProductNotFoundException::class => Response::HTTP_NOT_FOUND,
        StockAvailableNotFoundException::class => Response::HTTP_NOT_FOUND,
    ],
)]
class ProductStockMovements
{
    /**
     * Type of the group: `edition` for a single manual stock update, `orders` for the consecutive
     * movements generated by customer orders between two editions.
     */
    #[ApiProperty(openapiContext: ['type' => 'string', 'enum' => [StockMovement::EDITION_TYPE, StockMovement::ORDERS_TYPE]])]
    public string $type;

    public bool $edition;

    public bool $fromOrders;

    /**
     * @var int[]
     */
    #[ApiProperty(openapiContext: [
        'type' => 'array',
        'items' => ['type' => 'integer'],
        'description' => 'Ids of the stock movements of the group, one per movement (a single one for an edition, several for an orders group).',
    ])]
    public array $stockMovementIds;

    /**
     * @var int[]
     */
    #[ApiProperty(openapiContext: [
        'type' => 'array',
        'items' => ['type' => 'integer'],
        'description' => 'Ids of the stock entries the movements of the group apply to, aligned with stockMovementIds.',
    ])]
    public array $stockIds;

    /**
     * @var int[]
     */
    #[ApiProperty(openapiContext: [
        'type' => 'array',
        'items' => ['type' => 'integer'],
        'description' => 'Ids of the orders that generated the movements of the group, empty for an edition.',
    ])]
    public array $orderIds;

    /**
     * @var int[]
     */
    #[ApiProperty(openapiContext: [
        'type' => 'array',
        'items' => ['type' => 'integer'],
        'description' => 'Ids of the employees that made the movements of the group, empty when they were made by an API client.',
    ])]
    public array $employeeIds;

    /**
     * Name of the employee that made an edition movement, null for an orders group or a movement made by an API client.
     */
    public ?string $employeeName = null;

    /**
     * API clients that created the movements (empty when they were made by an employee,
     * or on PrestaShop versions that don't track the relation yet).
     *
     * @var int[]
     */
    #[ApiProperty(openapiContext: ['type' => 'array', 'items' => ['type' => 'integer']])]
    public array $apiClientIds = [];

    /**
     * @var string[]
     */
    #[ApiProperty(openapiContext: ['type' => 'array', 'items' => ['type' => 'string']])]
    public array $apiClientNames = [];

    /**
     * Sum of the quantity changes of the movements of the group (positive or negative).
     */
    public int $deltaQuantity;

    /**
     * Dates of the group keyed by their role: `add` for an edition (a single movement), `from` and `to`
     * for an orders group (the dates of its first and last movements).
     *
     * @var array<string, \DateTimeImmutable>
     */
    #[ApiProperty(openapiContext: [
        'type' => 'object',
        'additionalProperties' => ['type' => 'string', 'format' => 'date-time'],
        'description' => 'Dates keyed by their role: `add` for an edition, `from` and `to` for an orders group.',
        'example' => ['from' => '2026-01-15 10:00:00', 'to' => '2026-01-16 18:30:00'],
    ])]
    public array $dates;
}
